### ISSUE TITLE
global-issue-tracker

### ISSUE THREAD

**Issue by Wmorales01** [minecraft-anarchy/BlunixOfflineAuth#1]
### _Commands to Implement_

- [ ] `/auth register <Password>`
- [ ] `/auth login <Password>`
- [ ] `/auth unregister <Password>`
- [ ] `/auth changepassword <OldPassword> <NewPassword>`
- [ ] `/auth changeusername <OldNickName> <Password>` - Changes player's UUID in the playerdata folder to recover progress from a different username.
- [ ] `/auth recover <Email>` - Sends an email with a temporary password to change a forgotten password.

### _General Features_

- [ ] Ban IP after 3 failed login attempts.

**Comment by minecraft-anarchy** [comment]
>  Ban IP after 3 failed login attempts.
just log if there is a failed login attempt (preferably with the clients IP). I'll do the rest with fail2ban.

**Comment by minecraft-anarchy** [comment]
- [ ] please change the name from OfflineAuth to BlunixOfflineAuth: `Feb 19 20:01:42 minecraft-anarchy java[1768118]: [20:01:42] [Server thread/INFO]: [OfflineAuth] Enabling OfflineAuth v1.0`
- [ ] please do not restrict looking around / walking / breaking blocks / anything if the player did not use any /auth commands after joining. We will teleport the players to a secure location in the beginning where they can not do any damage
- [ ]
